version: '3.7'

services:
  web:
    build:
      context: ./olivier
      dockerfile: Dockerfile.prod
    expose:
      - 8000
      - 80
    volumes:
      - .:/usr/src/app
      - ./olivier:/home/app/web
    ports:
      - 3131:8000
    env_file:
      - .env.prod
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web