version: '3.7'

services:
  web:
    build:
      context: ./olivier
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      - URI=https://olivier.fly.dev
      - DEBUG=True
      - ALLOWED_HOSTS=*
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./olivier:/home/app/web
    ports:
      - '3131:8000'
