version: '3.7'

services:
  web:
    build:
      context: ./olivier
      dockerfile: Dockerfile.prod
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    ports:
      - 3131:8000
    env_file:
      - .env.prod