env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
globals:
  chrome: readonly
  $: readonly
  store: readonly # From utils/storageManager
  load: readonly # From utils/storageManager
  loadAll: readonly # From utils/storageManager
  clearPage: readonly # From utils/storageManager
  update: readonly # From utils/storageManager
  addHighlightError: readonly # From utils/errorManager
  highlight: readonly # From utils/highlight
  highlight_legacy: readonly # From utils/highlight_legacy
  HIGHLIGHT_CLASS: readonly # From utils/highlight
  DELETED_CLASS: readonly # From utils/highlight
  onHighlightMouseEnterOrClick: readonly # From hoverTools/hoverTools
  onHighlightMouseLeave: readonly # From hoverTools/hoverTools
  highlightOnSelection: readonly # From contentScripts/highlighterCursor
  _gaq: readonly # From config/analytics
ignorePatterns:
  - lib/*
  - config/*
parserOptions:
  ecmaVersion: 12
  sourceType: "module"
rules:
  accessor-pairs: error
  array-bracket-newline: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  array-element-newline: 'off'
  arrow-body-style: error
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
  camelcase: error
  class-methods-use-this: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly:
    - error
    - multi-line
    - consistent
  default-case: 'off'
  default-case-last: error
  default-param-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: 'off'
  eqeqeq: 'off'
  func-call-spacing: error
  func-name-matching: error
  func-names: 'off'
  func-style:
    - error
    - declaration
  function-paren-newline: error
  generator-star-spacing: error
  grouped-accessor-pairs: error
  guard-for-in: error
  id-denylist: error
  id-length: 'off'
  id-match: error
  implicit-arrow-linebreak: error
  indent: 'off'
  init-declarations: error
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing: 'off'
  linebreak-style:
    - error
    - windows
  lines-around-comment: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-len: 'off'
  max-nested-callbacks: error
  max-statements-per-line: 'off'
  new-cap: error
  new-parens: error
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-caller: error
  no-confusing-arrow: error
  no-console: error
  no-constructor-return: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: 'off'
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-loss-of-precision: error
  no-mixed-operators: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-nonoctal-decimal-escape: error
  no-octal-escape: error
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unsafe-optional-chaining: error
  no-unused-expressions: error
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  no-use-before-define: 'off'
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: 'off'
  no-void: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: 'off'
  object-shorthand: 'off'
  one-var: 'off'
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: 'off'
  padding-line-between-statements: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: 'off'
  prefer-exponentiation-operator: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-atomic-updates: error
  require-await: error
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi: error
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  sort-imports: 'off'
  sort-keys: 'off'
  space-before-blocks: error
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  strict: 'off'
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  vars-on-top: 'off'
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
