# Generated by Django 3.2.3 on 2021-12-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('from_id', models.IntegerField(default=0)),
                ('chat_id', models.IntegerField(default=0)),
                ('url', models.URLField(default='', max_length=1000)),
            ],
        ),
    ]
