# Generated by Django 3.2.3 on 2021-12-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2021-07-23 12:01"),
            preserve_default=False,
        ),
    ]
