# Generated by Django 4.0 on 2022-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0002_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(default='', max_length=1000, null=True),
        ),
    ]
