# Generated by Django 4.0 on 2022-01-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0003_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
