# Generated by Django 4.0 on 2022-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0004_alter_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
