# Generated by Django 4.0 on 2022-01-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0005_alter_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.JSONField(default='', max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=10000, null=True)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scroll.url')),
            ],
        ),
    ]
