# Generated by Django 4.0 on 2022-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0006_alter_url_url_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(default='', max_length=10000, null=True),
        ),
    ]
