# Generated by Django 4.0 on 2022-01-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0007_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scroll.url'),
        ),
    ]
