# Generated by Django 4.0 on 2022-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0008_alter_reply_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
