# Generated by Django 4.0 on 2022-01-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0009_url_text_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('from_id', models.IntegerField(default=0)),
                ('chat_id', models.IntegerField(default=0)),
                ('msg_type', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=10000, null=True)),
                ('msg_body', models.JSONField()),
                ('written_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scroll.url')),
            ],
        ),
    ]
