# Generated by Django 4.0 on 2022-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0012_extensiondata_extensionuser_telegramdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='mid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='cid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='fid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
