# Generated by Django 4.0 on 2022-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0014_remove_telegramdata_user_telegramdata_primary_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default='default_user', max_length=100, unique=True),
        ),
    ]
