# Generated by Django 4.0 on 2022-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionuser',
            name='uid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
