# Generated by Django 4.0 on 2022-01-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0017_rename_uid_extensionuser_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensiondata',
            old_name='url',
            new_name='text',
        ),
    ]
