# Generated by Django 4.0 on 2022-02-19 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0018_rename_url_extensiondata_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensiondata',
            name='sub_text',
        ),
        migrations.RemoveField(
            model_name='extensiondata',
            name='text',
        ),
        migrations.AddField(
            model_name='extensiondata',
            name='href',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='extensiondata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtensionHighlightMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorNode', models.TextField(max_length=1000, null=True)),
                ('anchorOffset', models.IntegerField(null=True)),
                ('color', models.TextField(max_length=1000, null=True)),
                ('container', models.TextField(max_length=10000, null=True)),
                ('focusNode', models.TextField(max_length=10000, null=True)),
                ('focusOffset', models.TextField(max_length=10000, null=True)),
                ('text', models.TextField(default='', max_length=1000000, null=True)),
                ('uuid', models.TextField(max_length=100, null=True)),
                ('edata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scroll.extensiondata')),
            ],
        ),
    ]
