# Generated by Django 4.0 on 2022-02-20 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0019_remove_extensiondata_sub_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionhighlightmetadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
