# Generated by Django 4.0 on 2022-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0020_extensionhighlightmetadata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensiondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='extensionhighlightmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
