# Generated by Django 4.0 on 2022-03-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0021_alter_extensiondata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scroll.user', unique=True),
        ),
    ]
