# Generated by Django 4.0 on 2022-03-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0022_alter_extensionuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionuser',
            name='uname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='extensionuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scroll.user'),
        ),
    ]
