# Generated by Django 4.0 on 2022-05-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0024_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='user',
            new_name='username',
        ),
    ]
